### ISSUE TITLE
[iOS] Not working with React Native 0.70

### ISSUE THREAD

**Issue by marcoburrometo** [JiriHoffmann/react-native-clusterer#18]
Hello!

Upgrading to react native 0.70 I have this error during build time:

`No member named 'throwJSError' in namespace 'facebook::jsi::detail'`

Looking at other repositories it seems like it's related to a old version of react native

**Comment by marcoburrometo** [comment]
https://github.com/JiriHoffmann/react-native-clusterer/pull/17
Didn't notice this pr. sorry
